Start using view component instead of mountain view
geeksforsocialchange/PlaceCal pull request #1834
Opened 2023-05-03 14:54 UTC by r-ferrier

fixes #867

### Description

- Adds view_component gem
- Refactors a component to use view component (I picked the hero image as it was simple and it would be obvious if it failed) 

### Notes

The file hierarchy for view component is subtly different - the `rb` file for the component needs to be in the root of the components folder, and any associated files can either be siblings or stored in a sibling folder. Everything must have the same name & that name must end `_component`

Aside from this it was very simple to set up and the boilerplate required for providing the component with the things it needs was significantly less. Hurrah!

2023-05-03 15:05 UTC, aaaaargZombies commented
Maybe a link in the README or something about how to generate a new component would be useful? or maybe I should just RTFM

2023-05-04 11:31 UTC, r-ferrier commented
@aaaaargZombies that's that script moved out of the makefile & added to the readme instead

2023-05-04 11:36 UTC, aaaaargZombies requested changes
I think we need to remove the `nvm` stuff from the make file as it breaks on my machine.

Otherwise it's working as it should. I don't have the files locally for the hero image but I can see it's pointing to the same url as production so I'm trusting it will work when it get's merged in.

thanks for bearing with me on this, I made it harder than it should have been

2023-05-04 11:36 UTC, aaaaargZombies commented on makefile
> +	nvm use && time sh -c "rails test --pride && rails test:system && rubocop"
ah same again, weird, anything you can think that I might be doing wrong?

2023-05-04 11:48 UTC, r-ferrier commented on makefile
> +	nvm use
Oh how annoying! Let's just take it out, it's not necessary for this and was just in there to try to prevent errors not cause them

2023-05-04 11:51 UTC, r-ferrier commented
I wonder if this is that thing with the symlink not working - I think it works alright on my machine but not on everyone's. Have removed anyway cos it's not necessary and v annoying! Argh computers!

2023-05-04 11:53 UTC, aaaaargZombies approved these changes
thank you! LGTM

2023-05-04 12:02 UTC, merged