Change how names appear in Devise mailer views
geeksforsocialchange/PlaceCal pull request #2102
Opened 2023-10-26 14:21 UTC by ivan-kocienski-gfsc

Closes #803 

If the user has any first name or last name fields set, use those, otherwise default to email (which must be present).

The invitation email (HTML version) has a PlaceCal logo image (position TBC).

Things to consider:
- email copy (for all emails)
- the sender email appears to be `support@placecal.org`
- Review use of data (like name) in email
- Think about legal/ privacy / footer information

2023-10-30 13:51 UTC, aaaaargZombies commented on app/models/user.rb
> +  def name_for_email
is this intended to be `name_or_email` ?

Looking at Katjas suggestion in the issue I think maybe this should return an empty string but would need to sort spacing with the `Hello` and the `,`

> Hello Dave Daverson,

vs

> Hello,

2023-10-30 13:55 UTC, aaaaargZombies approved these changes
I think this is good enough, I would like to see the name section changed but it's not blocking for me.

The rest of the email is a huge improvement and looks a lot more professional

2023-10-30 13:58 UTC, aaaaargZombies requested changes
sorry spoke too soon, looked at the tests and they are failing, think I commented where the problem is.

2023-10-30 13:58 UTC, aaaaargZombies commented on config/environments/development.rb
> +  Rails.logger.debug { "action_mailer.asset_host=#{asset_url}" }
oops look like this is crashing `debugger`?

2023-10-30 13:58 UTC, aaaaargZombies commented on config/environments/production.rb
> +  Rails.logger.debug { "action_mailer.asset_host=#{asset_url}" }
oops look like this is crashing `debugger`?

2023-10-30 16:00 UTC, kimadactyl commented
If we are gonna include the logo lets put it at the top and make it a lot smaller?

GFSC email for ref

<img width="687" alt="Screenshot 2023-10-30 at 16 00 38" src="https://github.com/geeksforsocialchange/PlaceCal/assets/511734/3e110a73-670e-4bca-8329-6706516f5a61">

2023-11-06 12:59 UTC, aaaaargZombies commented
after creating a new user I get redirected but hit this error

`undefined method `greeting_text' for #<ActionView::Base:0x00000000064668>`

coming from `app/views/devise/mailer/invitation_instructions.html.erb`

will the method / class need importing, it appears in the following views

```
app/views/devise/mailer/invitation_instructions.text.erb
app/views/devise/mailer/email_changed.html.erb
app/views/devise/mailer/unlock_instructions.html.erb
app/views/devise/mailer/password_change.html.erb
app/views/devise/mailer/reset_password_instructions.html.erb
app/views/devise/mailer/invitation_instructions.html.erb
app/views/devise/mailer/confirmation_instructions.html.erb
```

2023-11-06 13:47 UTC, ivan-kocienski-gfsc commented
Yeah i was hoping that i didn't have to write tests for this as the whole thing is complicated by devise.

2023-11-06 14:29 UTC, aaaaargZombies approved these changes
yes, the old turn it on and off again fixed that problem. sorry for the misdirection

LGTM!

2023-11-06 14:50 UTC, merged