[WIP] #885 sites neighbourhoods selector
geeksforsocialchange/PlaceCal pull request #887
Opened 2022-01-19 23:07 UTC by alexandria-gfsc

Does stuff. changes TBD

2022-01-19 23:08 UTC, alexandria-gfsc commented on app/views/admin/sites/_sites_neighbourhood_fields.erb
> +<%= f.hidden_field :relation_type, value: "Secondary" %>
lol ignore this file. didn't realise i hadn't deleted it. it was a misnamed file

2022-01-19 23:08 UTC, alexandria-gfsc commented on test/integration/admin/sites_integration_test.rb
> +      assert_select 'option', @number_of_neighbourhoods
this testing code is from prior commits. disregard

2022-01-25 16:13 UTC, kimadactyl commented on app/javascript/src/behaviors/behaviors.site.js
> +          multiple: false
You can use this to pull in fuzzy search results via ajax, check docs :)

2022-01-25 16:18 UTC, kimadactyl commented on app/views/admin/sites/_sites_neighbourhood_fields.html.erb
> +    <%= link_to_remove_association 'Remove Secondary Neighbourhood', f, class: "btn btn-danger" %>
let's tidy these up a bit with buttons to right of ward names, prob need to check bootstrap docs

2022-01-25 16:18 UTC, kimadactyl commented on app/views/admin/sites/_form.html.erb
> +      <%= link_to_add_association 'Add secondary', f, :sites_neighbourhoods, class: "btn btn-primary" %>
button text: Add Secondary Neighbourhood

2022-01-25 16:19 UTC, kimadactyl commented on app/javascript/packs/admin.js
> +require("@nathanvda/cocoon")
alphabatize these while we're here

2022-01-26 11:40 UTC, kimadactyl requested changes
See comments

2022-01-26 16:45 UTC, kimadactyl commented
Is this loading neighbourhoods via ajax?

2022-01-26 17:23 UTC, kimadactyl requested changes
- [ ] Make fuzzy search type input work on new selects
- [ ] All selects currently set to Abbey, Leics
- [ ] Make delete link just a link and tidy up UX a lil. i would put all of the inputs together in a fieldset

2022-02-01 13:23 UTC, alexandria-gfsc commented
Rebased on main

2022-02-01 15:01 UTC, kimadactyl requested changes
- [x] A few UX suggetions as per discord
- [x] Add better description text under headings
- [x] Fix create new site picker for main neighbourhood

2022-02-01 15:28 UTC, alexandria-gfsc commented
> * [x]  A few UX suggetions as per discord
> * [x]  Add better description text under headings

Done :)

> * [x]  Fix create new site picker for main neighbourhood

hmm it is not broken for me, it just doesn't display as a select2 element for whatever reason. Moved it to a `f.input` element so the rendering is fixed

2022-02-01 15:34 UTC, kimadactyl requested changes
Suggested controller tests:

- [ ] Create new site with primary neighbourhood only saves. Ditto for edit/update
- [ ] Create new site with both primary and secondary neighbourhood saves. Ditto for edit/update.
- [ ] Create new site with primary neighbourhood == secondary neighbourhood just saves the primary neighbourhood. Ditto for edit/update
- [ ] Same as above but with a few secondary neighbourhoods
- [ ] Primary neighbourhood is mandatory (might exist already)

2022-02-01 17:24 UTC, merged

2022-02-01 17:25 UTC, kimadactyl commented
Merged, controller tests created as another ticket